{
 "title": "Agent Monitoring Dashboard (VisualSwarm)",
 "description": "Dashboard to monitor a single agent in a VisualSwarm according to the github project with the same name",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "500ms",
 "panels": [
  { "title": "System Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU 1 usage [%]",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system_parameters",
     "select": [
      [
       { "params": [ "cpu_1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU 2 usage [%]",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system_parameters",
     "select": [
      [
       { "params": [ "cpu_2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU 3 usage [%]",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system_parameters",
     "select": [
      [
       { "params": [ "cpu_3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU 4 usage [%]",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system_parameters",
     "select": [
      [
       { "params": [ "cpu_4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Used Disk Space [%]",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "system_parameters",
     "select": [
      [
       { "params": [ "disk_percent" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Used Memory [%]",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "system_parameters",
     "select": [
      [
       { "params": [ "mem_percent" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU temperature [°C]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "system_parameters",
     "select": [
      [
       { "params": [ "cpu_temperature" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Control Parameters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Agent Velocity",
   "type": "graph",
   "description": "The graph shows the time evolution of the agent's velocity real time",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "Agent Velocity" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "control_parameters",
     "select": [
      [
       { "params": [ "agent_velocity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Processing Delay [ms]",
   "type": "stat",
   "description": "Processing delay from capturing a raw image with camera module to get the corresponding control parameters according to this frame.",
   "gridPos": { "h": 14, "w": 5, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "control_parameters",
     "select": [
      [
       { "params": [ "processing_delay" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heading Direction",
   "type": "graph",
   "description": "Heading direction of the agent",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Hading Angle" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "control_parameters",
     "select": [
      [
       { "params": [ "heading_angle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Vision",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Visual Projection Field",
     "type": "heatmap",
     "description": "The graph shows the visual projection field of the agent, i.e. the field has a value of 255 if a target object is detected at the given coordinate and 0 otherwise. \n\nUnits and Axes:\n   - x axis: time (timestamp)\n   - y axis: absolute position on the camera sensor in abstract px",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 10 },
     "targets": [
      {
       "alias": "$col",
       "measurement": "visual_projection_field",
       "query": "SELECT last(*) FROM \"visual_projection_field\" WHERE $timeFilter GROUP BY time($interval)",
       "select": [
        [
         { "params": [ "*" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}